### ISSUE TITLE
SDL2 integration

### ISSUE THREAD

**Issue by vheuken** [CptMonkeyFist/TinyTim#1]
Hey, I saw your post on the SDL2 forums about integrating SDL2 source. I have a project where I did just that, and got it to build on Windows, Linux, OS X, iOS, and Android, all with CMake. I haven't looked at the source code in a long time, but if you still want help, shoot me an email and I can help you with it.

I would've just replied to your forum post or PM'd you, but the forum didn't allow me to do either.

You can check it out here: https://github.com/vheuken/Purity2D
the SDL2 source is in extlibs/

Note: I added 85 lines to the SDL Cmake file, lines 4-89, to quickly hack in iOS and Android support, but that doesn't affect the rest.

**Comment by CptMonkeyFist** [comment]
I would appreciate your help in this regard. I am still a bit new to
writing my own CMake files, so please bear with my inexperience. If your
project is publicly hosted somewhere then I would like to check it out.
Otherwise feel free to download my sample code
<https://github.com/CptMonkeyFist/TinyTim> and modify it in order to get it
to work.

Nate

**Comment by vheuken** [comment]
You can check it out here: https://github.com/vheuken/Purity2D
the SDL2 source code is in extlibs/

Note: I added 85 lines to the SDL Cmake file, lines 4-89, to quickly hack in iOS and Android support, but that doesn't affect anything that you're doing.

It's been awhile since I looked at it, but you should look at the root project's CMakeLists.txt and the CMakeLists.txt in extlibs/

Let me know if you have any questions.

**Comment by CptMonkeyFist** [comment]
So I checked out your project, but I am having a bit of difficulty figuring
out where the "include_directories" call is for SDL2 in your cmake files.
In TinyTim cmake builds the Visual Studio solution just fine, but the SDL
include directory isn't being added to my TinyTim project dependencies. I
tried manually adding it by throwing an
'include_directories("external/SDL2/include")' command in my root
CMakeLists.txt but I get an error as a result.

How is your SDL include folder being added to your project's include path?

**Comment by vheuken** [comment]
Sorry, I know my CMake stuff is a big mess.

>How is your SDL include folder being added to your project's include path?

Line 37 in CMakeLists.txt:
```
add_subdirectory(extlibs)
```

Then on line 7 in extlibs/CMakeLists.txt:

```
add_subdirectory(SDL2-2.0.3)
```

> I am having a bit of difficulty figuring out where the "include_directories" call is for SDL2 in your cmake files.

Look in src/CMakeLists.txt file, lines 5 - 11

```
include_directories( 
    ${LIBS_INCLUDE_DIR}
    ${LIBS_INCLUDE_DIR}/lua-5.1.5/src
    ${LIBS_INCLUDE_DIR}/enet/include
    ${LIBS_INCLUDE_DIR}/SDL2-2.0.3/include
    ${LIBS_INCLUDE_DIR}/stb_image/
)
```

I should really consolidate the include_directories calls, since they're kinda all over the place.

**Comment by CptMonkeyFist** [comment]
I just figured out my problem and posted the solution on the forums. Thanks
for your help.

**Comment by vheuken** [comment]
:+1:
